# java ,mvn, docker 
---
- hosts: jenkins-slave
  become: true
  tasks:
  - name: Update the Ubuntu Repo
    apt:
      update-cache: true
      cache_valid_time: 3600
  - name: Install Java needed for slave
    apt:
      name: openjdk-11-jre
      state: present
  - name: Download Maven Package
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
      dest: /opt/
  - name: Extracting Maven Package
    unarchive:
      src: /opt/apache-maven-3.8.8-bin.tar.gz
      dest: /opt
      remote_src: yes
  - name: Download Java Package
    get_url:
      url: https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
      dest: /opt/
  - name: Extracting Java Package
    unarchive: 
      src: /opt/openjdk-17.0.2_linux-x64_bin.tar.gz
      dest: /opt
      remote_src: yes
  - name: Move to jdk-17
    command: mv /opt/jdk-17.0.2/ /opt/jdk-17/
  - name: Create /home/phanisekhar1404/jenkins folder
    file:
      path: /home/phanisekhar1404/jenkins
      state: directory
      mode: '0755'
      owner: phanisekhar1404
      group: phanisekhar1404
  - name: Install Docker 
    apt:
      name: docker.io
      state: present 
  - name: Add user 'phanisekhar1404' to docker group
    user:
      name: phanisekhar1404
      groups: docker
      append: yes

    
  
# Node, Docker, kubectl, helm ===> need to add 
